name: Build Branch
on:
  pull_request:

jobs:
  build:
    uses: flexbase-eng/.github/.github/workflows/typescript.build.yml@chore-add-publish-npm
    with:
      package_folder: output
      revision: ${{github.run_number}}
  
  coverage:
    needs: build
    uses: flexbase-eng/.github/.github/workflows/typescript.sonarcloud.yml@chore-add-publish-npm
    with:
      project_key: flexbase-eng_http-client-middleware
    secrets: inherit

  publish:
    needs: coverage
    uses: flexbase-eng/.github/.github/workflows/typescript.publish.npm.yml@chore-add-publish-npm
    with:
      tag: beta
    secrets: inherit
