name: Build
on:
  pull_request:

env:
  SONAR_PROJECT_KEY: flexbase-eng_http-client-middleware

jobs:
  build:
    uses: flexbase-eng/.github/.github/workflows/typescript.build.yml@main
  
  coverage:
    needs: build
    uses: flexbase-eng/.github/.github/workflows/typescript.sonarcloud.yml@main
    with:
      project_key: flexbase-eng_http-client-middleware

  publish:
    needs: coverage
    uses: flexbase-eng/.github/.github/workflows/typescript.publish.yml@main
    with:
      tag: beta
