name: Build
on:
  pull_request:

env:
  SONAR_ORG: flexbase
  SONAR_PROJECT_KEY: flexbase-eng_http-client-middleware
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: yarn install
      run: yarn install
    - name: yarn build
      run: yarn build
    - name: yarn test
      run: yarn test

  sonarcloud:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Disabling shallow clone is recommended for improving relevancy of reporting
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
     