name: Deploy Package
on:
  push:
    branches: main

jobs:
  build:
    uses: flexbase-eng/.github/.github/workflows/typescript.build.yml@main
  
  coverage:
    needs: build
    uses: flexbase-eng/.github/.github/workflows/typescript.sonarcloud.yml@main
    with:
      project_key: flexbase-eng_http-client-middleware
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish:
    needs: coverage
    uses: flexbase-eng/.github/.github/workflows/typescript.publish.yml@main
